### ISSUE TITLE
dock congregation list when screen size allows it

### ISSUE THREAD

**Issue by smcadams86** [rllc/llc-archives-react#3]
when the screen is large enough to support it, show the list of congregations.
when the screen is small, hide the list of congregations behind a menu

**Comment by smcadams86** [comment]
It looks as though `react-mdl` supports this out of the box : https://react-mdl.github.io/react-mdl/components/layout/

**Comment by timhillu** [comment]
My fix did not fix it.

**Comment by smcadams86** [comment]
closed via https://github.com/rllc/llc-archives-react/pull/22
